#======================= OpenCanary SMB Settings =======================

[global]
# domain or workgroup
    workgroup = canary.domain.local
# the browseable sharename
    server string = ""
# network hostname
    netbios name = CANARY02
# don't forward to dns
    dns proxy = no
    log file = /var/log/samba/log.all
# minimal logging
    log level = 0
# size in KB before rotation
    max log size = 100
# if error, do this action (won't work here)
    panic action = /usr/share/samba/panic-action %d
# standalone server, not domain joined
    server role = standalone
# uses local TDB to store account info
    passdb backend = tdbsam
    obey pam restrictions = yes
# don't sync unix accounts to smb
    unix password sync = no
# maps unknown users to a guest account instead of deny
    map to guest = bad user
    usershare allow guests = yes
# disable printer discovery
    load printers = no
# record selected file operations
    vfs object = full_audit
# the prepended audit message using variable substitutions
    full_audit:prefix = %I|%i|%U|%m|%L|%T
    	# https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html
        # %I    client IP
        # %i    local IP
    	# %U	session username
        # %m    NetBIOS name of client (may need additional config)
        # %L    NetBIOS name of the server
        # %T    current date and time
# list of VFS operations to be recorded if successful (only create_file, which is the base operation)
    full_audit:success = create_file
# list of VFS operations to be recorded if failure
    full_audit:failure = none
# output to syslog facility 7
    full_audit:facility = local7
# syslog severity level
    full_audit:priority = notice
# set the default to the Private share
    default service = Private

[Private]
    comment = Super Sensitive Documents
    path = /Private
# allows no password connections
    guest ok = yes
# not writeable
    read only = yes
    browseable = yes
    browse list = yes
